pragma solidity ^0.5.0;

contract Counter{
  //uint256 the default size in Solidity, the state of the contracts unsigned
  uint256 public value;

  event Increased(uint256 newValue);

  //getter to access value, its generated by the use of the public keyword declaration
  function increase() public{
    //increase function to increment value
    value = value +1;
    
    //event used to signal when a modification of value has occured
    emit Increased(value);
  }
}